# Python Data Cleaning

## Import Libraries

In [11]:
import pandas as pd

In [12]:
import numpy as np

Step 1: Load the Data

In [13]:
df = pd.read_csv("../Dataset/raw_data/Loan_Default.csv")

In [14]:
print(df)

            ID  year loan_limit             Gender approv_in_adv loan_type  \
0        24890  2019         cf  Sex Not Available         nopre     type1
1        24891  2019         cf               Male         nopre     type2
2        24892  2019         cf               Male           pre     type1
3        24893  2019         cf               Male         nopre     type1
4        24894  2019         cf              Joint           pre     type1
...        ...   ...        ...                ...           ...       ...
148665  173555  2019         cf  Sex Not Available         nopre     type1
148666  173556  2019         cf               Male         nopre     type1
148667  173557  2019         cf               Male         nopre     type1
148668  173558  2019         cf             Female         nopre     type1
148669  173559  2019         cf             Female         nopre     type1

       loan_purpose Credit_Worthiness open_credit business_or_commercial  ...  \
0                p1                l1        nopc                  nob/c  ...
1                p1                l1        nopc                    b/c  ...
2                p1                l1        nopc                  nob/c  ...
3                p4                l1        nopc                  nob/c  ...
4                p1                l1        nopc                  nob/c  ...
...             ...               ...         ...                    ...  ...
148665           p3                l1        nopc                  nob/c  ...
148666           p1                l1        nopc                  nob/c  ...
148667           p4                l1        nopc                  nob/c  ...
148668           p4                l1        nopc                  nob/c  ...
148669           p3                l1        nopc                  nob/c  ...

        credit_type  Credit_Score  co-applicant_credit_type    age  \
0               EXP           758                       CIB  25-34
1              EQUI           552                       EXP  55-64
2               EXP           834                       CIB  35-44
3               EXP           587                       CIB  45-54
4              CRIF           602                       EXP  25-34
...             ...           ...                       ...    ...
148665          CIB           659                       EXP  55-64
148666          CIB           569                       CIB  25-34
148667          CIB           702                       EXP  45-54
148668          EXP           737                       EXP  55-64
148669          CIB           830                       CIB  45-54

        submission_of_application        LTV Region Security_Type  Status  \
0                         to_inst  98.728814  south        direct       1
1                         to_inst        NaN  North        direct       1
2                         to_inst  80.019685  south        direct       0
3                        not_inst  69.376900  North        direct       0
4                        not_inst  91.886544  North        direct       0
...                           ...        ...    ...           ...     ...
148665                    to_inst  71.792763  south        direct       0
148666                   not_inst  74.428934  south        direct       0
148667                   not_inst  61.332418  North        direct       0
148668                    to_inst  70.683453  North        direct       0
148669                   not_inst  72.849462  North        direct       0

       dtir1
0       45.0
1        NaN
2       46.0
3       42.0
4       39.0
...      ...
148665  48.0
148666  15.0
148667  49.0
148668  29.0
148669  44.0

[148670 rows x 34 columns]

In [15]:
print(df.head())

      ID  year loan_limit             Gender approv_in_adv loan_type  \
0  24890  2019         cf  Sex Not Available         nopre     type1
1  24891  2019         cf               Male         nopre     type2
2  24892  2019         cf               Male           pre     type1
3  24893  2019         cf               Male         nopre     type1
4  24894  2019         cf              Joint           pre     type1

  loan_purpose Credit_Worthiness open_credit business_or_commercial  ...  \
0           p1                l1        nopc                  nob/c  ...
1           p1                l1        nopc                    b/c  ...
2           p1                l1        nopc                  nob/c  ...
3           p4                l1        nopc                  nob/c  ...
4           p1                l1        nopc                  nob/c  ...

   credit_type  Credit_Score  co-applicant_credit_type    age  \
0          EXP           758                       CIB  25-34
1         EQUI           552                       EXP  55-64
2          EXP           834                       CIB  35-44
3          EXP           587                       CIB  45-54
4         CRIF           602                       EXP  25-34

   submission_of_application        LTV Region Security_Type  Status dtir1
0                    to_inst  98.728814  south        direct       1  45.0
1                    to_inst        NaN  North        direct       1   NaN
2                    to_inst  80.019685  south        direct       0  46.0
3                   not_inst  69.376900  North        direct       0  42.0
4                   not_inst  91.886544  North        direct       0  39.0

[5 rows x 34 columns]

In [16]:
print(df.shape)

(148670, 34)

Step 2: Check Data Types

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148670 entries, 0 to 148669
Data columns (total 34 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ID                         148670 non-null  int64
 1   year                       148670 non-null  int64
 2   loan_limit                 145326 non-null  object
 3   Gender                     148670 non-null  object
 4   approv_in_adv              147762 non-null  object
 5   loan_type                  148670 non-null  object
 6   loan_purpose               148536 non-null  object
 7   Credit_Worthiness          148670 non-null  object
 8   open_credit                148670 non-null  object
 9   business_or_commercial     148670 non-null  object
 10  loan_amount                148670 non-null  int64
 11  rate_of_interest           112231 non-null  float64
 12  Interest_rate_spread       112031 non-null  float64
 13  Upfront_charges            109028 non-null  float64
 14  term                       148629 non-null  float64
 15  Neg_ammortization          148549 non-null  object
 16  interest_only              148670 non-null  object
 17  lump_sum_payment           148670 non-null  object
 18  property_value             133572 non-null  float64
 19  construction_type          148670 non-null  object
 20  occupancy_type             148670 non-null  object
 21  Secured_by                 148670 non-null  object
 22  total_units                148670 non-null  object
 23  income                     139520 non-null  float64
 24  credit_type                148670 non-null  object
 25  Credit_Score               148670 non-null  int64
 26  co-applicant_credit_type   148670 non-null  object
 27  age                        148470 non-null  object
 28  submission_of_application  148470 non-null  object
 29  LTV                        133572 non-null  float64
 30  Region                     148670 non-null  object
 31  Security_Type              148670 non-null  object
 32  Status                     148670 non-null  int64
 33  dtir1                      124549 non-null  float64
dtypes: float64(8), int64(5), object(21)
memory usage: 38.6+ MB

Step 3: Check missing values

In [18]:
missing = df.isnull().sum()

In [19]:
print(missing)

ID                               0
year                             0
loan_limit                    3344
Gender                           0
approv_in_adv                  908
loan_type                        0
loan_purpose                   134
Credit_Worthiness                0
open_credit                      0
business_or_commercial           0
loan_amount                      0
rate_of_interest             36439
Interest_rate_spread         36639
Upfront_charges              39642
term                            41
Neg_ammortization              121
interest_only                    0
lump_sum_payment                 0
property_value               15098
construction_type                0
occupancy_type                   0
Secured_by                       0
total_units                      0
income                        9150
credit_type                      0
Credit_Score                     0
co-applicant_credit_type         0
age                            200
submission_of_application      200
LTV                          15098
Region                           0
Security_Type                    0
Status                           0
dtir1                        24121
dtype: int64

In [20]:
missing_percent = (missing/len(df)) * 100

In [21]:
missing_percent

ID                            0.000000
year                          0.000000
loan_limit                    2.249277
Gender                        0.000000
approv_in_adv                 0.610749
loan_type                     0.000000
loan_purpose                  0.090133
Credit_Worthiness             0.000000
open_credit                   0.000000
business_or_commercial        0.000000
loan_amount                   0.000000
rate_of_interest             24.509989
Interest_rate_spread         24.644515
Upfront_charges              26.664425
term                          0.027578
Neg_ammortization             0.081388
interest_only                 0.000000
lump_sum_payment              0.000000
property_value               10.155378
construction_type             0.000000
occupancy_type                0.000000
Secured_by                    0.000000
total_units                   0.000000
income                        6.154571
credit_type                   0.000000
Credit_Score                  0.000000
co-applicant_credit_type      0.000000
age                           0.134526
submission_of_application     0.134526
LTV                          10.155378
Region                        0.000000
Security_Type                 0.000000
Status                        0.000000
dtir1                        16.224524
dtype: float64

In [22]:
missing_table = pd.DataFrame({
    'Missing_Count' : missing,
    'Missing_Percent' : missing_percent
})

In [23]:
missing_table

                           Missing_Count  Missing_Percent
ID                                     0         0.000000
year                                   0         0.000000
loan_limit                          3344         2.249277
Gender                                 0         0.000000
approv_in_adv                        908         0.610749
loan_type                              0         0.000000
loan_purpose                         134         0.090133
Credit_Worthiness                      0         0.000000
open_credit                            0         0.000000
business_or_commercial                 0         0.000000
loan_amount                            0         0.000000
rate_of_interest                   36439        24.509989
Interest_rate_spread               36639        24.644515
Upfront_charges                    39642        26.664425
term                                  41         0.027578
Neg_ammortization                    121         0.081388
interest_only                          0         0.000000
lump_sum_payment                       0         0.000000
property_value                     15098        10.155378
construction_type                      0         0.000000
occupancy_type                         0         0.000000
Secured_by                             0         0.000000
total_units                            0         0.000000
income                              9150         6.154571
credit_type                            0         0.000000
Credit_Score                           0         0.000000
co-applicant_credit_type               0         0.000000
age                                  200         0.134526
submission_of_application            200         0.134526
LTV                                15098        10.155378
Region                                 0         0.000000
Security_Type                          0         0.000000
Status                                 0         0.000000
dtir1                              24121        16.224524

In [24]:
print(missing_table[missing_table['Missing_Count']>0])

                           Missing_Count  Missing_Percent
loan_limit                          3344         2.249277
approv_in_adv                        908         0.610749
loan_purpose                         134         0.090133
rate_of_interest                   36439        24.509989
Interest_rate_spread               36639        24.644515
Upfront_charges                    39642        26.664425
term                                  41         0.027578
Neg_ammortization                    121         0.081388
property_value                     15098        10.155378
income                              9150         6.154571
age                                  200         0.134526
submission_of_application            200         0.134526
LTV                                15098        10.155378
dtir1                              24121        16.224524

Step 4: Handle missing values (column by column)

Fill numeric columns with meadian (median is safer then mean, since it ignores extreme high values)

In [25]:
print(df.describe())

                  ID      year   loan_amount  rate_of_interest  \
count  148670.000000  148670.0  1.486700e+05     112231.000000
mean    99224.500000    2019.0  3.311177e+05          4.045476
std     42917.476598       0.0  1.839093e+05          0.561391
min     24890.000000    2019.0  1.650000e+04          0.000000
25%     62057.250000    2019.0  1.965000e+05          3.625000
50%     99224.500000    2019.0  2.965000e+05          3.990000
75%    136391.750000    2019.0  4.365000e+05          4.375000
max    173559.000000    2019.0  3.576500e+06          8.000000

       Interest_rate_spread  Upfront_charges           term  property_value  \
count         112031.000000    109028.000000  148629.000000    1.335720e+05
mean               0.441656      3224.996127     335.136582    4.978935e+05
std                0.513043      3251.121510      58.409084    3.599353e+05
min               -3.638000         0.000000      96.000000    8.000000e+03
25%                0.076000       581.490000     360.000000    2.680000e+05
50%                0.390400      2596.450000     360.000000    4.180000e+05
75%                0.775400      4812.500000     360.000000    6.280000e+05
max                3.357000     60000.000000     360.000000    1.650800e+07

              income   Credit_Score            LTV         Status  \
count  139520.000000  148670.000000  133572.000000  148670.000000
mean     6957.338876     699.789103      72.746457       0.246445
std      6496.586382     115.875857      39.967603       0.430942
min         0.000000     500.000000       0.967478       0.000000
25%      3720.000000     599.000000      60.474860       0.000000
50%      5760.000000     699.000000      75.135870       0.000000
75%      8520.000000     800.000000      86.184211       0.000000
max    578580.000000     900.000000    7831.250000       1.000000

               dtir1
count  124549.000000
mean       37.732932
std        10.545435
min         5.000000
25%        31.000000
50%        39.000000
75%        45.000000
max        61.000000

In [26]:
print(df.dtypes)

ID                             int64
year                           int64
loan_limit                    object
Gender                        object
approv_in_adv                 object
loan_type                     object
loan_purpose                  object
Credit_Worthiness             object
open_credit                   object
business_or_commercial        object
loan_amount                    int64
rate_of_interest             float64
Interest_rate_spread         float64
Upfront_charges              float64
term                         float64
Neg_ammortization             object
interest_only                 object
lump_sum_payment              object
property_value               float64
construction_type             object
occupancy_type                object
Secured_by                    object
total_units                   object
income                       float64
credit_type                   object
Credit_Score                   int64
co-applicant_credit_type      object
age                           object
submission_of_application     object
LTV                          float64
Region                        object
Security_Type                 object
Status                         int64
dtir1                        float64
dtype: object

In [27]:
df['rate_of_interest'] = df['rate_of_interest'].fillna(df['rate_of_interest'].median())

In [28]:
df['rate_of_interest'].isnull().sum()

np.int64(0)

In [29]:
df['Interest_rate_spread'] = df['Interest_rate_spread'].fillna(df['Interest_rate_spread'].median())

In [30]:
df['Interest_rate_spread'].isnull().sum()

np.int64(0)

In [31]:
df['Upfront_charges'] = df['Upfront_charges'].fillna(df['Upfront_charges'].median())

In [32]:
df['Upfront_charges'].isnull().sum()

np.int64(0)

In [33]:
df['term'] = df['term'].fillna(df['term'].median())

In [34]:
df['term'].isnull().sum()

np.int64(0)

In [35]:
print(df['property_value'].isnull().sum())

15098

In [36]:
df['property_value'] = df['property_value'].fillna(df['property_value'].median())

In [37]:
print(df['property_value'].isnull().sum())

0

In [38]:
df['income'].isnull().sum()

np.int64(9150)

In [39]:
df['income'] = df['income'].fillna(df['income'].median())

In [40]:
df['income'].isnull().sum()

np.int64(0)

In [41]:
print(df['LTV'].isnull().sum())

15098

In [42]:
df['LTV'] = df['LTV'].fillna(df['LTV'].median())

In [43]:
df['LTV'].isnull().sum()

np.int64(0)

In [44]:
df['dtir1'].isnull().sum()

np.int64(24121)

In [45]:
df['dtir1'] = df['dtir1'].fillna(df['dtir1'].median())

In [46]:
df['dtir1'].isnull().sum()

np.int64(0)

Fill text/category columns with mode (most frequent value)

In [47]:
print(df.isnull().sum())

ID                              0
year                            0
loan_limit                   3344
Gender                          0
approv_in_adv                 908
loan_type                       0
loan_purpose                  134
Credit_Worthiness               0
open_credit                     0
business_or_commercial          0
loan_amount                     0
rate_of_interest                0
Interest_rate_spread            0
Upfront_charges                 0
term                            0
Neg_ammortization             121
interest_only                   0
lump_sum_payment                0
property_value                  0
construction_type               0
occupancy_type                  0
Secured_by                      0
total_units                     0
income                          0
credit_type                     0
Credit_Score                    0
co-applicant_credit_type        0
age                           200
submission_of_application     200
LTV                             0
Region                          0
Security_Type                   0
Status                          0
dtir1                           0
dtype: int64

In [48]:


df['loan_limit'] = df['loan_limit'].fillna(df['loan_limit'].mode()[0])

df['approv_in_adv'] = df['approv_in_adv'].fillna(df['approv_in_adv'].mode()[0])

df['loan_purpose'] = df['loan_purpose'].fillna(df['loan_purpose'].mode()[0])

df['Neg_ammortization'] = df['Neg_ammortization'].fillna(df['Neg_ammortization'].mode()[0])

df['age'] = df['age'].fillna(df['age'].mode()[0])

df['submission_of_application'] = df['submission_of_application'].fillna(df['submission_of_application'].mode()[0])

In [49]:
df.rename(columns={'co-applicant_credit_type':'co_applicant_credit_type'})

,ID,year,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,...,credit_type,Credit_Score,co_applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,24890,2019,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,24891,2019,cf,Male,nopre,type2,p1,l1,nopc,b/c,...,EQUI,552,EXP,55-64,to_inst,75.135870,North,direct,1,39.0
2,24892,2019,cf,Male,pre,type1,p1,l1,nopc,nob/c,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,24893,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,24894,2019,cf,Joint,pre,type1,p1,l1,nopc,nob/c,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148665,173555,2019,cf,Sex Not Available,nopre,type1,p3,l1,nopc,nob/c,...,CIB,659,EXP,55-64,to_inst,71.792763,south,direct,0,48.0
148666,173556,2019,cf,Male,nopre,type1,p1,l1,nopc,nob/c,...,CIB,569,CIB,25-34,not_inst,74.428934,south,direct,0,15.0
148667,173557,2019,cf,Male,nopre,type1,p4,l1,nopc,nob/c,...,CIB,702,EXP,45-54,not_inst,61.332418,North,direct,0,49.0
148668,173558,2019,cf,Female,nopre,type1,p4,l1,nopc,nob/c,...,EXP,737,EXP,55-64,to_inst,70.683453,North,direct,0,29.0
148669,173559,2019,cf,Female,nopre,type1,p3,l1,nopc,nob/c,...,CIB,830,CIB,45-54,not_inst,72.849462,North,direct,0,44.0

Step 5: Check and remove duplicate rows

In [50]:
duplicate_count = df.duplicated().sum()

print("duplicate found: ",duplicate_count)

duplicate found:  0

Step 6: Fix the age column

In [51]:
age_mapping = {
    '<25' : 20,
    '25-34' : 30,
    '35-44' : 40,
    '45-54' : 50,
    '55-64' : 60,
    '65-74' : 70,
    '>74' : 78
}

In [52]:
df['Age_Estimate'] = df['age'].map(age_mapping)

In [53]:
df['Age_Estimate'].isnull().sum()

np.int64(0)

In [54]:
df['Age_Estimate'].isnull().sum()

np.int64(0)

Step 7: Handle Outliers in LTV

In [55]:
print("Rows with LTV above 100:", (df['LTV']>100).sum())

Rows with LTV above 100: 1799

In [56]:
# We cap (limit) LTV at 100, since LTV above 100% is not realistic for most standard loans
df['LTV'] = df['LTV'].apply(lambda x: 100 if x > 100 else x)

Step 8: Rename Status to Clear Labels

In [57]:
df['Default_Status'] = df['Status'].map({1: 'Yes', 0: 'No'})

Step 9: Create Extra Realistic Columns

In [58]:
# 1. EMI - calculated using a simplified loan EMI formula
df['Interest_Rate_Monthly'] = df['rate_of_interest'] / 12 / 100
df['EMI'] = (df['loan_amount'] * df['Interest_Rate_Monthly'] * 
             (1 + df['Interest_Rate_Monthly'])**df['term']) / \
            ((1 + df['Interest_Rate_Monthly'])**df['term'] - 1)

# 2. Branch - randomly assign one of 10 branch codes (simulating real bank branches)
np.random.seed(42)
branch_list = ['BR001','BR002','BR003','BR004','BR005','BR006','BR007','BR008','BR009','BR010']
df['Branch'] = np.random.choice(branch_list, size=len(df))

# 3. Loss_Amount - only applies to defaulted loans, estimated as a portion of loan amount
df['Loss_Amount'] = np.where(df['Default_Status'] == 'Yes', 
                              df['loan_amount'] * 0.35, 0)

# 4. Recovery_Amount - only applies to defaulted loans, the rest the bank managed to recover
df['Recovery_Amount'] = np.where(df['Default_Status'] == 'Yes', 
                                  df['loan_amount'] * 0.20, 0)

Step 10: Convert Data Types Properly

In [59]:
df['year'] = df['year'].astype(int)
df['loan_amount'] = df['loan_amount'].astype(float)
df['income'] = df['income'].astype(float)
df['Credit_Score'] = df['Credit_Score'].astype(int)
df['term'] = df['term'].astype(int)

Step 11: Final Check

In [60]:
print(df.isnull().sum().sum())  # should print 0 if all missing values are handled
print(df.shape)

1
(148670, 41)

In [61]:
print(df.isnull().sum())

ID                           0
year                         0
loan_limit                   0
Gender                       0
approv_in_adv                0
loan_type                    0
loan_purpose                 0
Credit_Worthiness            0
open_credit                  0
business_or_commercial       0
loan_amount                  0
rate_of_interest             0
Interest_rate_spread         0
Upfront_charges              0
term                         0
Neg_ammortization            0
interest_only                0
lump_sum_payment             0
property_value               0
construction_type            0
occupancy_type               0
Secured_by                   0
total_units                  0
income                       0
credit_type                  0
Credit_Score                 0
co-applicant_credit_type     0
age                          0
submission_of_application    0
LTV                          0
Region                       0
Security_Type                0
Status                       0
dtir1                        0
Age_Estimate                 0
Default_Status               0
Interest_Rate_Monthly        0
EMI                          1
Branch                       0
Loss_Amount                  0
Recovery_Amount              0
dtype: int64

In [62]:
problem_row = df[df['EMI'].isnull()]
print(problem_row[['loan_amount', 'rate_of_interest', 'term']])

       loan_amount  rate_of_interest  term
36272     406500.0               0.0   324

If the interest rate is 0%, then logically, the EMI is simply the loan amount divided evenly across the number of months — no interest to add.

In [63]:
# Check the exact row first (good practice, confirms before fixing)
print(df[df['EMI'].isnull()][['loan_amount', 'rate_of_interest', 'term']])

# Fix: if rate_of_interest is 0, EMI = loan_amount / term (simple division, no interest)
df.loc[df['EMI'].isnull(), 'EMI'] = df['loan_amount'] / df['term']

# Confirm the fix worked
print(df['EMI'].isnull().sum())

       loan_amount  rate_of_interest  term
36272     406500.0               0.0   324
0

In [64]:
print(df.isnull().sum().sum())

0

Step 12: Save the cleaned file

In [ ]:
df.to_csv('../Dataset/Cleaned_data/loan_data_cleaned.csv', index=False)
print("Cleaned file saved successfully!")

Cleaned file saved successfully!